version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
           name: Install Requirements 
           command: |
             apk add python3
             apk add py3-pip
             pip3 install flask
