version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
           name: Install Requirements 
           command: |
             apk add python
             apk add pip
             pip install flask
